---
- name: Ensure path exists for Saxon-HE maven artifact
  file:
    path: /opt/saxon-he
    state: directory

- name: Install Saxon-HE
  maven_artifact:
    group_id: net.sf.saxon
    artifact_id: Saxon-HE
    version: "{{ saxon_he_version }}"
    repository_url: https://repo1.maven.org/maven2
    dest: /opt/saxon-he/saxon-he.jar
    mode: 0755
